const UPDATE_TOURNAMENT_NAME = 'tournamentName'
const UPDATE_TOURNAMENT_FORMAT = 'tournamentFormat'
const UPDATE_TEAMS = 'teams'
const UPDATE_IS_BRACKET_UP_TO_DATE = 'isBracketUpToDate'
const UPDATE_SINGLE_ELIMINATION_DATA = 'singleEliminationData'
const UPDATE_BEST_OF_SINGLE = 'bestOfSingle'
const UPDATE_ROUND_ROBIN_DATA = 'roundRobinData'
const UPDATE_ROUND_ROBIN_SCOREBOARD = 'roundRobinScoreBoard'
const UPDATE_BEST_OF_ROUND_ROBIN = 'bestOfRoundRobin'
const UPDATE_LINKS = 'links'
const UPDATE_UPPER_BRACKET = 'upperBracket'
const UPDATE_LOWER_BRACKET = 'lowerBracket'
const UPDATE_BEST_OF_DOUBLE = 'bestOfDouble'

export {
    UPDATE_TOURNAMENT_NAME, 
    UPDATE_TOURNAMENT_FORMAT, 
    UPDATE_TEAMS,
    UPDATE_IS_BRACKET_UP_TO_DATE,
    UPDATE_SINGLE_ELIMINATION_DATA,
    UPDATE_BEST_OF_SINGLE,
    UPDATE_ROUND_ROBIN_DATA, 
    UPDATE_ROUND_ROBIN_SCOREBOARD, 
    UPDATE_BEST_OF_ROUND_ROBIN,
    UPDATE_LINKS,
    UPDATE_UPPER_BRACKET,
    UPDATE_LOWER_BRACKET,
    UPDATE_BEST_OF_DOUBLE
}